stages:
  - build
  - deploy

variables:
  AZURE_WEBAPP_NAME: "FRF-API"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

build:
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y azure-cli
    - az webapp config appsettings set --name $AZURE_WEBAPP_NAME --settings WEBSITE_WEBDEPLOY_USE_SCM=true
    - az webapp deployment source config-zip --name $AZURE_WEBAPP_NAME --src "$AZURE_WEBAPP_PACKAGE_PATH/publish.zip" --build-arg PublishProfile=AZUREAPPSERVICE_PUBLISHPROFILE_323025339955443BAB484CC939B564CE
    

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y azure-cli
    - az webapp config appsettings set --name $AZURE_WEBAPP_NAME --settings WEBSITE_WEBDEPLOY_USE_SCM=true
    - az webapp deployment source config-zip --name $AZURE_WEBAPP_NAME --src "$AZURE_WEBAPP_PACKAGE_PATH/publish.zip" --build-arg PublishProfile=AZUREAPPSERVICE_PUBLISHPROFILE_323025339955443BAB484CC939B564CE
