# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Publish backend 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - git-pipeline

env:
  AZURE_WEBAPP_NAME: EFRF-API
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./backend/FRF.sln
        
      - name: Build
        run: dotnet build ./backend/FRF.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./backend/FRF.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DD8523320A474C5E99320F9D52AD3376 }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
